Building dockerfile pulls arch binary from repo

diff --git a/loki/Dockerfile b/loki/Dockerfile
--- a/loki/Dockerfile
+++ b/loki/Dockerfile
@@ -1,15 +1,26 @@
 ARG BUILD_FROM
 
-# https://hub.docker.com/r/grafana/loki
-# https://github.com/grafana/loki/releases
-FROM grafana/loki:2.2.0 as build
-
 # hadolint ignore=DL3006
 FROM $BUILD_FROM
 
+# https://github.com/grafana/loki/releases
+ENV LOKI_VERSION 2.2.0
+
 # Add Loki
-COPY --from=build /usr/bin/loki /usr/bin/loki
 RUN set -eux; \
+    APKARCH="$(apk --print-arch)"; \
+    case "$APKARCH" in \
+    x86_64)  BINARCH='amd64' ;; \
+    armhf)   BINARCH='arm' ;; \
+    armv7)   BINARCH='arm' ;; \
+    aarch64) BINARCH='arm64' ;; \
+    *) echo >&2 "error: unsupported architecture ($APKARCH)"; exit 1 ;; \
+    esac; \
+    \
+    curl -J -L -o /tmp/loki.zip "https://github.com/grafana/loki/releases/download/v${LOKI_VERSION}/loki-linux-${BINARCH}.zip"; \
+    unzip /tmp/loki.zip -d /usr/bin; \
+    mv /usr/bin/loki-linux-${BINARCH} /usr/bin/loki; \
+    chmod a+x /usr/bin/loki; \
     loki -version;
 
 # add Nginx
